### ISSUE TITLE
StepWrapper is not working after update

### ISSUE THREAD

**Issue by facusantillo** [unickq/allure-nunit#10]
After the update to 1.0.0, my entire implementation of allure is broken.

The very first thing is the way the instance of allure lifecycle is working. We have a custom method for the start and stop steps:

`public string StartStep(string name)
        {
            var x = TestContext.CurrentContext.Result;
            string uuid = Guid.NewGuid().ToString();
            StepResult step = new StepResult()
            {
                name = name,
                stage = Stage.finished,
                status = Status.passed
            };
            AllureLifecycle.Instance.StartStep(uuid, step);
            return uuid;
        }`

This is throwing exceptions. We try to use the new stepWrapper `AllureNUnitHelper.WrapInStep(() => action) ` but is throwing a System.ArgumentNullException.

Is there a way to fix this without refactoring the whole solution? (I have currently more than 600 test cases and we really want to avoid a mayor refactor in our sln)

Thanks in advance

**Comment by facusantillo** [comment]
I found this in the Nunit Console Log:

`System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at NUnit.Allure.Core.AllureNUnitHelper.<>c__DisplayClass21_2.<UpdateTestDataFromAttributes>b__2(TestResult x)
   at Allure.Commons.AllureLifecycle.UpdateTestCase(String uuid, Action`1 update)
   at Allure.Commons.AllureLifecycle.UpdateTestCase(Action`1 update)
   at NUnit.Allure.Core.AllureNUnitHelper.UpdateTestDataFromAttributes()
   at NUnit.Allure.Core.AllureNUnitHelper.StopTestCase()
   at NUnit.Allure.Core.AllureNUnitHelper.StopAll(Boolean isWrapedIntoStep)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 59`

**Comment by unickq** [comment]
Hi,

I’m sorry to hear that - the entire approach of allure getation changed a little bit 😕

Wrapper for Action methods should work everywhere between setup and teardown.

Can you please share an example of code or what/where exactly you are trying to create step

**Comment by facusantillo** [comment]
We have a custom method in charge of starting the allureStep and stop it. The code is the following:

public string StartStep(string name)
        {
            var x = TestContext.CurrentContext.Result;
            string uuid = Guid.NewGuid().ToString();
            StepResult step = new StepResult()
            {
                name = name,
                stage = Stage.finished,
                status = Status.passed
            };
            AllureLifecycle.Instance.StartStep(uuid, step);
            return uuid;
        }

Then we call a custom method called StopStep() with the uuid of the step we started previously:
 
public void StopStep(string uuid)
        {
            AllureLifecycle.Instance.StopStep(uuid);
        }

 This was working just fine until the new version. The instance of the AllureLifecycle is throwing exceptions everywhere. We remove the custom methods and try the example you have in the project with the AllureNUnitHelper.WrapInStep() method. 

The thing is when the test finishes in the Nunit console, it's throwing an exception.

I really need to fix this, otherwise i can't update to new version and stick in the previous one :(

**Comment by unickq** [comment]
I see the code how you start and stop steps, but I don’t know where you call it. I mean I don’t understand where you use steps - before/after/in test.

@facusantillo can you provide more details? [AllureNUnitHelper.WrapInStep](https://github.com/unickq/allure-nunit/blob/master/src/Core/AllureNUnitHelper.cs#L325*) does exactly the same your methods do. Are you trying to execute steps after Allure testcase stopped?

**Comment by unickq** [comment]
@facusantillo , any updates?
