### ISSUE TITLE
TestCase attribute aint working without "Category"

### ISSUE THREAD

**Issue by Onebitl0st** [unickq/allure-nunit#11]
Hello!
After i've updated allure-nunit to 1.0.0 - i found some strange thing.
Then im running my tests with resharper - everything went good, but then im using console runner - i got 

> Error : APITests.StorageAndCacheTests.Tests.test
> System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
>    at NUnit.Allure.Core.AllureNUnitHelper.<>c__DisplayClass21_2.<UpdateTestDataFromAttributes>b__2(TestResult x)
>    at Allure.Commons.AllureLifecycle.UpdateTestCase(String uuid, Action`1 update)
>    at Allure.Commons.AllureLifecycle.UpdateTestCase(Action`1 update)
>    at NUnit.Allure.Core.AllureNUnitHelper.UpdateTestDataFromAttributes()
>    at NUnit.Allure.Core.AllureNUnitHelper.StopTestCase()
>    at NUnit.Allure.Core.AllureNUnitHelper.StopAll(Boolean isWrapedIntoStep)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

 .

Found a way to reproduce this - 

```
[Category("Debug")]
[Test(Description = "test")]
[TestCase("1", TestName = "test")]
public void Test(string num)
  {
            Assert.AreEqual("1", num);
        
   }
   <- this test wont work

[Category("Debug")]
        [Test(Description = "test")]
        [TestCase("1", TestName = "test", Category = "Debug")]
        public void Test(string num)
        {
            Assert.AreEqual("1", num);
        }

 <- this will be ok.
```

Can you fix this? Or i should add this param for each one of my testcases?

i think error somethere around

> if (_test.Properties.ContainsKey("Category"))
>             {
>                 var list = _test.Properties["Category"];
>                 AllureLifecycle.UpdateTestCase(x => x.labels.Add(Label.Tag(list[0].ToString())));
>             }
>  in         private void UpdateTestDataFromAttributes()

Best regards,
Dmitry

**Comment by unickq** [comment]
Thanks, @Onebitl0st .

That's really weird. I've created a new project with the code you posted and can't reproduce it.
![1 0 0](https://user-images.githubusercontent.com/6696821/44213288-082a4180-a176-11e8-9b5a-7ed372f3f542.png)

Can you provide more details? Like setup/teardowns, etc

**Comment by Onebitl0st** [comment]
Well, in common there is a setup teardown in our projects, but i reproduced that in same new class as you.

Now my VS updating, and i cant do a thing for a while :D but then i take a look at your code, i have one idea - if you'll change your [TestFixture] to [TestFixture(Category = "asd")], as on my code, i dont rly know, but i changed all of them sometimes for Allure :D maybe this will provide reproducing?

**Comment by unickq** [comment]
```[TestFixture(Category = "asd")``` doesn't set tags from category all but that's a different issue :D
Still can't get the issue you raised.

NET46?

**Comment by Onebitl0st** [comment]
Yeah, net461, do you run tests with category? or just as all tests?

**Comment by Onebitl0st** [comment]
![380d467891026c56f156530c0d6528cd](https://user-images.githubusercontent.com/7286958/44215218-a7e9ce80-a17a-11e8-8122-2ded2f29385c.png)

So yeah, i think it is)

**Comment by unickq** [comment]
Made a quick fix for Category in testFixture - will upload it soon,

> do you run tests with category? or just as all tests?
All tests, no params in console runner

Noticed that code
```
if (_test.Properties.ContainsKey(PropertyNames.Category))
                AllureLifecycle.UpdateTestCase(x =>
                    x.labels.Add(Label.Tag(_test.Properties.Get(PropertyNames.Category).ToString())));
```
for tests with attribute [TestCase] doesn't work as it's a different ITest. Maybe that's the issue

**Comment by Onebitl0st** [comment]
@unickq , I think you'll reproduce this too, if you'd run with category

**Comment by unickq** [comment]
Actually, it worked with cat too 😩  I'll test again with a new build

New ver: https://www.nuget.org/packages/NUnit.Allure/1.0.1

**Comment by unickq** [comment]
I reproduced the issue - will check it when I have time :)

**Comment by unickq** [comment]
@Onebitl0st 
Please test https://www.nuget.org/packages/NUnit.Allure/1.0.2 and close issue if it's ready 🛩

**Comment by Onebitl0st** [comment]
@unickq Checked! Thanks a lot for fix!
