### ISSUE TITLE
When the allure result is generated, the "AllureLifecycle.Instance.AllureConfiguration.Directory" property is ignored

### ISSUE THREAD

**Issue by iamfreid** [unickq/allure-nunit#13]
I'm trying to configure different allure result directories depending on the configuration being run. I have the following code:
```c#
private void AllureConfig()
        {
            string resultPath = "C:\\ProgramData\\BaseTrade\\TestsMetaData\\OtcMain_stable";
            AllureLifecycle.Instance.AllureConfiguration.Directory = resultPath;
        }
````

and standart json config:
```json
{
  "allure": {
    "directory": "allure-results",
    "links": [
      "https://example.org/{issue}",
      "https://example.org/{tms}"
    ]
  }
}
```
But when generating allure result, the output directory is always allure-results.

Allure.Commons 2.3.67.1
NUnit.Allure 1.0.0

**Comment by unickq** [comment]
@iamfreid 

I think it's a question to https://github.com/allure-framework/allure-csharp and @Bakanych
But I'll check that

**Comment by Bakanych** [comment]
@iamfreid Can you please use json config for that:
https://github.com/allure-framework/allure-csharp/wiki/Allure.Commons#configuration

**Comment by iamfreid** [comment]
@Bakanych  Yes, so far i'm using json config and transforming

**Comment by unickq** [comment]
Linking to https://github.com/allure-framework/allure-csharp/issues/18
Because the fix of it requires an ability to set custom json location and probably ability to set result dir :)

**Comment by unickq** [comment]
Closed due changes in https://github.com/allure-framework/allure-csharp/issues/18
Now it could be done as:
```cs
var configJson = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "config.json");
if (File.Exists(configJson))
{
    Environment.SetEnvironmentVariable("ALLURE_CONFIG", configJson);
    AllureLifecycle.Instance.CleanupResultDirectory();
}
```
tested in .netCore as well
