### ISSUE TITLE
Could I configure path to allureConfig.json

### ISSUE THREAD

**Issue by aydkz** [unickq/allure-nunit#15]
I switched my project to NUnit.Allure. Before that my allureConfig.json file was located in project's root folder.
Now when i'm trying to run tests, I've got error "could not find file allureconfig.json", because it should be in the allure.coomons package folder. Is there a way to configure nunit to look for a allureConfig.json in the project folder?

**Comment by unickq** [comment]
Make sure you copy json to OutDir. This is where [Allure.Commons](https://github.com/allure-framework/allure-csharp/wiki/Allure.Commons) tries to find the configuration for itself

![image](https://user-images.githubusercontent.com/6696821/45689226-1647f500-bb5c-11e8-961c-7abf148193a9.png)

**Comment by aydkz** [comment]
As I understood, Allure.Commons tries to find file near the Allure.Commons.dll. But it's not in project folder, so my allureConfig also not in the project
![image](https://user-images.githubusercontent.com/43376581/45692239-f8ca5980-bb62-11e8-9bd2-a4152d99fa27.png)

**Comment by unickq** [comment]
Allure.Commons.dll should be in a project folder. It's a dependency

Visual Studio Ver 2017?
Project Target Framework is net.std2.0?

**Comment by aydkz** [comment]
I run tests in jenkins. It restores packages every time it runs. And when packages are restored, there is no allureConfig file in allure.commons folder and the occures
![image](https://user-images.githubusercontent.com/43376581/45735348-42ad5100-bbf0-11e8-8f82-6fcd0ffc6420.png)

**Comment by unickq** [comment]
Can you share packages.config or .csproj so I can see what packages you have installed?

**Comment by aydkz** [comment]
![image](https://user-images.githubusercontent.com/43376581/45739475-ca4c8d00-bbfb-11e8-95ee-0be903f1b42d.png)

**Comment by unickq** [comment]
What's your target framework? NetCore?

**Comment by aydkz** [comment]
Problem is solved. Probably it was due to incompatibility between Allure.Commons and Nunit.Allure versions. Deleting Allure.Commons solved the problem
