### ISSUE TITLE
Basic usage - How to generate Allure results

### ISSUE THREAD

**Issue by petre-c** [unickq/allure-nunit#16]
I've tried running tests with NUnit.ConsoleRunner but allure-results directory is missing and the TestResults.xml it generates doesn't contain Allure specific attributes.

What are the steps required to generate Allure results?

Thanks!

**Comment by petre-c** [comment]
Same applies when I run tests with ReSharper test runner - can't find allure-results anywhere

**Comment by unickq** [comment]
Hi @petrechitashvili 

Check this out https://docs.qameta.io/allure/#_report_generation to generate a report.

If you use default config of allureConfig.json Resharper path would be smth like ```AppData\Local\JetBrains\Installations\ReSharperPlatformVs15_1ab876a6\allure-results```.

Also you can always access **AllureLifeCycle.Instance.ResultsDirectory** property to see the dir with Allure results

**Comment by petre-c** [comment]
Thank you SO MUCH @unickq - you made my day!
You have a great one too :-)
