### ISSUE TITLE
Attribute cannot be null in parametrized tests

### ISSUE THREAD

**Issue by neparij** [unickq/allure-nunit#17]
https://github.com/unickq/allure-nunit/blob/351e31e2bd55d6cd8ca592a09ddd6e94e2344b58/src/Core/AllureNUnitHelper.cs#L239

this._test.Arguments[i].toString() throws System.NullReferenceException if this._test.Arguments[i] == null

For example:
Code of test to reproduce:

        [Test, Combinatorial]
        [AllureStory("Example")]
        public void TestExample(
            [Range(1, 3)] int valA,
            [Values((object)null, 2)] int? valB
            )
        {
                Assert.Equals(valA, valB);
        }

**Comment by unickq** [comment]
@neparij thanks, I'll check it

**Comment by unickq** [comment]
@neparij , fixed. Thanks for the bug
https://www.nuget.org/packages/NUnit.Allure/1.0.5

**Comment by neparij** [comment]
Thanks! :)
