### ISSUE TITLE
Overview Environment

### ISSUE THREAD

**Issue by yotsubakoiwai** [unickq/allure-nunit#20]
Hi Nick,
This is more of a question than issue...
In the overview section of the report, how can I pull the correct environment from a config file?
Say I have the following settings:
<add key="Platform" value="Android" />
<add key="os_version" value="5.0" />
<add key="deviceName" value="Samsung Galaxy S6"/>

Then on next run I have iOS, etc.
How do I set that in the Environments section so they're grouped together like 
Samsung Galaxy S6, Android OS 5.0
iPhone XS, iOS 10.0
.
..
...

**Comment by unickq** [comment]
Make suites, subsuites if you want to see test divided by it.
![image](https://user-images.githubusercontent.com/6696821/58082635-13584500-7bc0-11e9-8753-88335a8a22b4.png)

What is the environment, what is a config file?

**Comment by yotsubakoiwai** [comment]
hello nick!
yeah i want something like that.. but under the environment section in the report not as suites...

**Comment by unickq** [comment]
So here are the docs https://docs.qameta.io/allure/#_environment

**Comment by yotsubakoiwai** [comment]
hi nick.. i had a look at the docs, but still confuses me...
how does the tests be grouped in those suites above per device?
i tried doing that, running the same test case for Samsung and iOS and the report ends up displaying only the latest one. The first one pass, but second one failed.. then report only shows the failed one (because they have the same test name??).. not both? is there a way to overwrite it, i.e. display both results grouped per suite?

These are the results of both the test runs in the allure-results folder. 

![image](https://user-images.githubusercontent.com/26672384/58216895-d6608f80-7d32-11e9-9493-1cf8ce7c77d4.png)

![image](https://user-images.githubusercontent.com/26672384/58216975-26d7ed00-7d33-11e9-866b-09e90d6fb37a.png)
