### ISSUE TITLE
[AllureStep] not working in NUnit 3 [OneTimeSetUp] method

### ISSUE THREAD

**Issue by darthKwisatzHaderach** [unickq/allure-nunit#23]
I have OneTimeSetUp method in test suite:
```csharp
[OneTimeSetUp]
public void OneTimeSetUp()
{
    var page = new Page(Driver);
    page.GetPage();
}
```
And following page method:
```csharp
[AllureStep("Get page")]
public void GetPage()
{
    Driver.Navigate().GoToUrl("https://www.google.com/");
}
```
When I run this suite with nunit, I receive "System.ArgumentNullException" at page.GetPage();
It seems like a bug.

Project dependencies:
NUnit (3.12.0)
    NUnit.Allure (1.0.6.2)
      Allure.Commons (>= 2.3.64.1)
      NUnit (>= 3.10.1)
    NUnit.Console (3.10.0)
      NUnit.ConsoleRunner (>= 3.10)
      NUnit.Extension.NUnitProjectLoader (>= 3.6)
      NUnit.Extension.NUnitV2Driver (>= 3.7)
      NUnit.Extension.NUnitV2ResultWriter (>= 3.6)
      NUnit.Extension.TeamCityEventListener (>= 1.0.6)
      NUnit.Extension.VSProjectLoader (>= 3.8)
    NUnit.Extension.NUnitProjectLoader (3.6.0)
    NUnit.Extension.NUnitV2ResultWriter (3.6.0)
    NUnit.Allure.Steps (1.0.7.1)
      AspectInjector (>= 2.2.1)
      NUnit.Allure (>= 1.0.6)
    NUnit.ConsoleRunner (3.10)
    NUnit.Extension.NUnitV2Driver (3.8)
    NUnit.Extension.TeamCityEventListener (1.0.7)
    NUnit.Extension.VSProjectLoader (3.8)

**Comment by unickq** [comment]
Can you share the full code? Or at least significant parts where you set up Driver.
netcore? netframework?

**Comment by unickq** [comment]
Unfortunately, you can't use any allure methods in OneTimeSetUp/OneTimeTearDown.

The reason - this plugin is built over [TestAction](https://github.com/nunit/docs/wiki/Action-Attributes) which mean allure initialization happens in `BeforeTest(ITest test)` - so you can get Aluure in OneTimeSetUp

**Comment by darthKwisatzHaderach** [comment]
Is there any workaround for this limitation?
I have a solution with tests and page objects. Some test suites use page objects in OneTimeSetUp.
So, I added [AllureStep] to page object method and realize that some tests falls.
I really like allure report and it features, but I can't invent how to apply it on my solution because of this limitation. Any ideas? :)

**Comment by unickq** [comment]
I don't think so.
What's the point of Page setup in OneTimeSetUp btw?

**Comment by darthKwisatzHaderach** [comment]
For example, in my SUT (system under test) I have project entity. I write tests that check default project settings. So, there is no need to create project before each test. I do it in OneTimeSetUp and all tests use this project.
```csharp
[OneTimeSetUp]
public void OneTimeSetUp()
{
    var projectsPage = new ProjectsPage(Driver);
    page.CreateProject();
    var projectSettingsPage = projectsPage.OpenProject();
}

[Test]
public void ArchiveTabTest()
{
    Assert.IsTrue(projectSettingsPage.IsProjectContainsArchiveTab());
}
```

**Comment by darthKwisatzHaderach** [comment]
Also OneTimeSetUp can be used for Login.

**Comment by unickq** [comment]
Do you run tests simultaneously?

**Comment by darthKwisatzHaderach** [comment]
You mean in parallel? Yes

**Comment by unickq** [comment]
Personally, I don't see the reason to perform actions like this in Global setup methods.
But it's your coding style and so on.

As I said you can't use Allure there. By design

**Comment by darthKwisatzHaderach** [comment]
Can you at least somehow handle [AllureStep] call in [OneTimeSetUp] and prevent the suite from falling?

**Comment by darthKwisatzHaderach** [comment]
Or is it an antipattern?

**Comment by unickq** [comment]
It is.
You can create own version of [[AllureStep] attribute](https://github.com/unickq/allure-nunit/tree/master/src/allure-nunit-steps) where you can catch anything you need and wrap your logic.

**Comment by darthKwisatzHaderach** [comment]
Ok, thank you for explanation! And also thanks for you contribution in integration between .net, nunit with allure report. It's really useful!

**Comment by alex-dylda** [comment]
@darthKwisatzHaderach , Hello! How are you using Allure with Nunit 3.12.0? It says to me that "Could not load file or assembly 'nunit.framework, Version=3.10.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference."
Once I rollback NUnit to 3.10.1 version everything is ok.
I use:
Allure.Commons 2.4.2.4
NUnit.Allure 1.0.6.2

**Comment by unickq** [comment]
@alex-dylda net-framework?

**Comment by alex-dylda** [comment]
@unickq yes, net 4.7.2

**Comment by unickq** [comment]
@alex-dylda update NUnit and its PublicKeyToken and Version in csproj ItemGroup -> Reference -

**Comment by alex-dylda** [comment]
@unickq I'm using PackageReference, in csproj file I have:
```
 <PackageReference Include="NUnit">
      <Version>3.10.1</Version>
    </PackageReference>
```
When I updating it to 
```
    <PackageReference Include="NUnit">
      <Version>3.12.0</Version>
    </PackageReference>
```
I'm getting "Could not load file or assembly 'nunit.framework, Version=3.10.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies." at runtime.

**Comment by unickq** [comment]
@alex-dylda 
Like I said before - update 
> 'nunit.framework, Version=3.10.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' 

it manually. Your project references to 3.10 while you have 3.12 after update

For 3.12 it looks like `<Reference Include="nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">`

**Comment by alex-dylda** [comment]
@unickq I've updated manually. 
Set in csproj file:
```
  <Reference Include="NUnit.Framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.Framework.3.12.0.0\lib\net45\NUnit.Framework.dll</HintPath>
    </Reference>
```
And updated Nunit (not framework) to 3.12.0.
But still see the same error. I guess that problem is in Nunit.Allure library, it depends on 3.10.1 and my manual update of Nunit.Framework will not help here.

**Comment by unickq** [comment]
@alex-dylda 

I tested your config - set NET472 proj, installed nunit-allure with NuGet.
Ran tests with preinstalled NUnit 3.10. Worked fine.
Updated NUnit to 3.12 using VS. Still fine.

> I guess that problem is in Nunit.Allure library

So it's not, because it works for everybody but you :)

Search for 3.10 in your project. Remove bin,obj folders. Or recreate the project from scratch

**Comment by alex-dylda** [comment]
@unickq Hmmm, thank you for the research, will try to find in my project who references to 3.10.1

**Comment by AlbertoBN** [comment]
While referencing NUnit.Allure and Allure.Commons from Nuget the problem with nunit.framework persists. Local referencing is not an  option... And this is a new project built from scratch Any insights?

**Comment by unickq** [comment]
@AlbertoBN 
can you give more details?
what net version, vs, which versions of NUnit you use, etc?

**Comment by AlbertoBN** [comment]
Sorry for the delay. I am preparing a fusion log for you.

**Comment by AlbertoBN** [comment]
Attached please find a fresh fusion log. 
[FusionLog.txt](https://github.com/unickq/allure-nunit/files/5149020/FusionLog.txt)

Thank you in advance

**Comment by unickq** [comment]
@AlbertoBN 

`Calling assembly : NUnit.Allure, Version=1.0.6.2, Culture=neutral, PublicKeyToken=null.`
Is that reproducible with [1.0.9](https://www.nuget.org/packages/NUnit.Allure/1.0.9) ?

The same issue as https://github.com/unickq/allure-nunit/issues/23#issuecomment-588092682. In your config you use `nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb`, while `nunit.framework, Version=3.10.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb` is not found.

**Comment by AlbertoBN** [comment]
I installed 1.0.9 via Nuget....
![image](https://user-images.githubusercontent.com/2389018/91702968-2a873000-eb82-11ea-9c64-95b8082a3569.png)

**Comment by AlbertoBN** [comment]
I tried your suggestions in the other comments and had no luck.... something is weird since I installed the latest allure.nunit but it still looks for the old one and this is the first time I am using allure....

I took the liberty to browse the 1.0.9 tag... and I found this:

```
<ItemGroup>
    <PackageReference Include="Allure.Commons" Version="2.3.64.1" />
    <PackageReference Include="NUnit" Version="3.10.1" />
  </ItemGroup>
```
Could this be the reason?`

**Comment by unickq** [comment]
> Could this be the reason?`

It worked for everyone before. Once 3.11 released, and after.

Anyway, I've just published [1.0.11](https://www.nuget.org/packages/NUnit.Allure) with updated NUnit dep. Give it a try

**Comment by AlbertoBN** [comment]
I will thanks. I have a nasty habit of making a clean build on the CI system. :)

**Comment by AlbertoBN** [comment]
Success! Thank you!
