### ISSUE TITLE
Is it possible to add the method's parameters to report with the help of AllureStep?

### ISSUE THREAD

**Issue by IZaiarnyi** [unickq/allure-nunit#25]
```C#
        [AllureStep("I login with email = {email} and  pass {pass} ")]
        public BackgroundChecksSteps Login(string email, string pass)
        {
               new LoginPage().login(email, pass);
        }
```

**Comment by unickq** [comment]
Hi @IZaiarnyi 

That won't work with [AllureStep]. But you can use

```csharp
public BackgroundChecksSteps Login(string email, string pass)
{
    return AllureLifecycle.Instance.WrapInStep(() => { new LoginPage().login(email, pass); }, $"I login with email = {email} and  pass {pass} ");
}
```

**Comment by IZaiarnyi** [comment]
Thank you, for your response. This works, but the readability of code becomes worse( Probably, it makes sense to add this functionality into AllureStep attribute?

**Comment by unickq** [comment]
@IZaiarnyi feel free to make a PR
https://github.com/unickq/allure-nunit/blob/master/src/allure-nunit-steps/AllureStepAspect.cs

**Comment by unickq** [comment]
@IZaiarnyi 
added this feature in [1.0.9](https://github.com/unickq/allure-nunit/releases/tag/1.0.9)
parsing parameters values by indexes

```csharp
namespace xxx
{
    [AllureNUnit]
    public class Tests
    {
        [Test]
        public void Test1()
        {
            StepSample("user", "pwd123");
        }

        [AllureStep("Login with user {0} and password {1}")]
        public void StepSample(string username, string password)
        {
            Console.WriteLine(username);
            Console.WriteLine(password);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/6696821/77404638-b4a0c080-6dba-11ea-8534-c24181243449.png)

**Comment by ProAntix** [comment]
@unickq great feature, however, when trying implement it I get the following error when entering the method with the [AllureStep] above it: 
![image](https://user-images.githubusercontent.com/15614791/77438234-78328c00-6ddd-11ea-90d6-8b0a0d9c578d.png)
Any idea how I can fix this?

Thanks.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=NUnit.Allure.Steps
  StackTrace:
   at NUnit.Allure.Steps.AllureStepAspect.WrapStep(String name, MethodBase methodBase, Object[] arguments, Func`2 method)
   at Fenergo.API.Tests.TestBase.__a$_around_CreateCobCase_100663395_w_0(Object[] )
   at Fenergo.API.Tests.TestBase.CreateCobCase(String leName, String template, String formatValue, String leKey, String userKey)
   at Fenergo.API.Tests.TestBase.<CheckForLeOrCreate>d__80.MoveNext() in C:\git\Fenergo.API.Tests.2\Tests\TestBase.cs:line 760

**Comment by unickq** [comment]
@ProAntix 
Well, no idea. Such a complex async code 😃. It can be one of the dependencies, like allure-csharp, aspect, etc. Or my code, idk. I have never run async NUnit test with allure before. 

But let's have a look.
Can you create a smaller example of the equal async code for me to debug?

**Comment by ProAntix** [comment]
@unickq I'll try get that done tomorrow.

Where can I get a list of the full dependencies, don't think I've got all of those installed.

**Comment by IZaiarnyi** [comment]
Wow, thank you
