### ISSUE TITLE
Test name is created as a step and steps inside the tests are substeps

### ISSUE THREAD

**Issue by sourcecode14** [unickq/allure-nunit#26]
Test name is created as a step and steps inside the tests are substeps .

Ideally , test name should not be a test step . 

Awaiting your reply

![image](https://user-images.githubusercontent.com/32709214/77317286-eb31f900-6d30-11ea-9ec6-e0c9eae618d6.png)

**Comment by unickq** [comment]
Hi @sagardaine 

Didn't get what you mean. Please provide code sample with your expectations

**Comment by sourcecode14** [comment]
If you refer a screenshot, "navigate to search page" is a test case name that is being shown as a test step in the report and actual test steps as substeps.

the expectation is test case name should not be a considered as step

**Comment by unickq** [comment]
So you just want to see steps without navigaToSearchPage root!

**Comment by sourcecode14** [comment]
Yes

**Comment by unickq** [comment]
The allure nesting structure is the following:
```
Container
    Test
       Step
```
You can't have steps without tests.
