### ISSUE TITLE
How to add a screenshot to each test step

### ISSUE THREAD

**Issue by sourcecode14** [unickq/allure-nunit#27]
I wanted to add a screenshot to each test step in allure report, is it possible ?

**Comment by unickq** [comment]
Yes, you can add an attachment in each step

```csharp
[AllureNUnit]
internal class Class1
{
    [Test]
    public void AssertIgnore()
    {
        Console.WriteLine("Assert");
        Step1();
        Step2();
    }

    [AllureStep("Step with attachment 1")]
    public void Step1()
    {
        AllureLifecycle.Instance.AddAttachment("x.jpg", "attachment");
    }


    public void Step2()
    {
        AllureLifecycle.Instance.WrapInStep(
            () => { AllureLifecycle.Instance.AddAttachment(".jpg", "attachment"); },
            "Step with attachment 2");
    }
}
```

![image](https://user-images.githubusercontent.com/6696821/77380655-53f69100-6d84-11ea-9381-7a3d753c85cb.png)

**Comment by sourcecode14** [comment]
My Code 
```csharp
Allure.Commons.AllureLifecycle.Instance.WrapInStep(() =>
                {
                    Allure.Commons.AllureLifecycle.Instance.AddAttachment(".jpg", "attachment");
                    Driver.Navigate().GoToUrl(Util.Settings.GetURL());
                }, "Load URL");
```

Will this add attachment after the step execution "Driver.Navigate().GoToUrl(Util.Settings.GetURL());"

As this step might fail or pass but I want to capture a screenshot for that step

**Comment by unickq** [comment]
Of course, this won't. Your page opening code is executed before the attachment adds.

**Comment by sourcecode14** [comment]
I did not get you, 

my add attachment code is written before the page opening code.

My requirement is to attach the screenshot for each step

**Comment by unickq** [comment]
Where do you execute this code? Please give me a full example of the code that fails.
Stack traces, error messages, etc
