### ISSUE TITLE
If test contains await, then [AllureStep] failed with System.ArgumentNullException : Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by redfirefox** [unickq/allure-nunit#28]
This code given exception:
[Test]
public async Task Test()
{		
	await Task.Delay(1000);
	Hello();		
}

[AllureStep]
public void Hello()
{			
}

System.ArgumentNullException : Value cannot be null. (Parameter 'key')
  Stack Trace: 
    ConcurrentDictionary`2.ThrowKeyNullException()
    ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
    ConcurrentDictionary`2.get_Item(TKey key)
    AllureStorage.Get[T](String uuid)
    AllureStorage.AddStep(String parentUuid, String uuid, StepResult stepResult)
    AllureLifecycle.StartStep(String parentUuid, String uuid, StepResult stepResult)
    AllureLifecycle.StartStep(String uuid, StepResult result)
    AllureStepAspect.WrapStep(String name, MethodBase methodBase, Object[] arguments, Func`2 method)
    Tests.__a$_around_Hello_100663386_w_0(Object[] )
    Tests.Hello()

But this code - successful:
[Test]
public async Task Test()
{			
	Task.Delay(1000).GetAwaiter().GetResult();
	Hello();						
}

**Comment by unickq** [comment]
I reproduced this issue, debugged through allure.commons. 
But can't answer why with `await` new step we create can't find its parent.
![image](https://user-images.githubusercontent.com/6696821/81289237-bb377e80-906e-11ea-9539-9a38e8d366f3.png)

**Comment by ProAntix** [comment]
I have this issue too. Very perplexing.

**Comment by unickq** [comment]
@ProAntix  @redfirefox 
Created issue https://github.com/allure-framework/allure-csharp/issues/106 in base repo

**Comment by unickq** [comment]
Another example - https://github.com/unickq/allure-nunit/issues/41#issue-929270390 by @bloodgang94 

```csharp
[AllureNUnit]
    public class AllureAsyncTest
    {
        [Test]
        public async Task Test()
        {
            var testUser = await GenerateAsync();
            AllureLifecycle.Instance.WrapInStep(() =>
            {
                Assert.AreEqual(testUser, "a");
            });
        }

        public static async Task<string> GenerateAsync()
        {
            return await Task.Run(() => Generate());
        }

        public static string Generate()
        {
            Thread.Sleep(1000);
            return "AAA";
        }
    }
```
```

System.ArgumentNullException : Value cannot be null. (Parameter 'key')
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
```

**Comment by NaZaRKIN123** [comment]
Any updates here?

**Comment by EvgenyMarchuk** [comment]
The same issue and critical for me! Pls, solve the problem! Thanks

**Comment by unickq** [comment]
please follow https://github.com/allure-framework/allure-csharp/tree/main/Allure.NUnit
since all the code there - should be much easier to fix
