### ISSUE TITLE
MaxLimit attribute doesn't logged in allure

### ISSUE THREAD

**Issue by Eatric** [unickq/allure-nunit#31]
When test failed by MaxLimit attribute, allure does not logging that, it is marked like passed

**Comment by unickq** [comment]
Need more details. Code to reproduce

**Comment by Eatric** [comment]
> Need more details. Code to reproduce

Code to reproduce: https://pastebin.com/chVTqunq

![image](https://user-images.githubusercontent.com/16813968/94894615-67508a80-0492-11eb-9f36-6f2df9554805.png)
![image](https://user-images.githubusercontent.com/16813968/94894654-76cfd380-0492-11eb-8831-e2074487bedc.png)

**Comment by unickq** [comment]
That's very interesting. NUnit reports actual test status. And only after it marks it as failed with MaxLimit
![image](https://user-images.githubusercontent.com/6696821/94912290-1d769d00-04b0-11eb-8269-69fe6f50a6fb.png)

Need to see how MaxLimit works

**Comment by unickq** [comment]
**MaxTime** is built over [AfterTestCommand](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Commands/AfterTestCommand.cs), while this plugin with [ITestAction](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Commands/TestActionItem.cs). Which means that allure executed with inner test context, while MaxTime changes test result after the test finished.
