### ISSUE TITLE
Changing the version of an assembly reference is not allowed during debugging

### ISSUE THREAD

**Issue by epoxit** [unickq/allure-nunit#35]
Hi!
My project: Net.Core, NUnit. 
Adding this link to the project makes debugging impossible. That is, literally adding the line 
`var qwe = true; `
anywhere results in the error:
`Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version = 2.0.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51' changed version to '2.1.0.0.`

Maybe NUnit.Allure.Steps internally links to https://www.nuget.org/packages/AspectInjector/
and it's trying to generate and rebuild some assemblies in memory at compile time?

**Comment by unickq** [comment]
Can you attach project archive for me to reproduce?

**Comment by andrematosfundao** [comment]
@epoxit i have the same issue. how did you fix this?

**Comment by epoxit** [comment]
[andrematosfundao](https://github.com/andrematosfundao), sorry, I don't remember :(
