### ISSUE TITLE
Value cannot be null. (Parameter 'key') async Task

### ISSUE THREAD

**Issue by bloodgang94** [unickq/allure-nunit#41]
Hey! Error The value cannot be null. (Parameter key) if the test method is asynchronous
![image](https://user-images.githubusercontent.com/63465285/123277546-4136b300-d517-11eb-9d09-db0ad59342fa.png)
![image](https://user-images.githubusercontent.com/63465285/123277564-4693fd80-d517-11eb-8f74-16ff99adfced.png)

**Comment by unickq** [comment]
It's a part of core lib https://github.com/allure-framework/allure-csharp/issues/106

**Comment by unickq** [comment]
It's a part of core lib https://github.com/allure-framework/allure-csharp/issues/106
already described in https://github.com/unickq/allure-nunit/issues/28
