### ISSUE TITLE
Could not install package 'NUnit.Allure 1.0.14'

### ISSUE THREAD

**Issue by PriyaFa** [unickq/allure-nunit#42]
I am using Visual Studio 2017 .net framework 4.8.

 < TargetFrameworkVersion >v4.5.2< /TargetFrameworkVersion>

When I install the nuget package Nunit.Allure Then I get error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'NUnit.Allure 1.0.14'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

I am trying to get a report out of automated api tests using - nunit , c# , restsharp

When I read about Allure it is exactly what am looking for. But am struck on the installation step. Can anyone please help ?

**Comment by PriyaFa** [comment]
when i changed the targetframework to 4.6.1 nuget package got installed

**Comment by unickq** [comment]
@PriyaFa
I believe it doesn't support the old 4.5.2 if it worked with 4.6.1

4.5.2 is 7 years old, any specific reason you need to use that?

**Comment by unickq** [comment]
no actions
