### ISSUE TITLE
Cannot find "AllureNUnit" attribute after update of "NUnite.Allure" nuget package from 1.0.14 to 1.2.0

### ISSUE THREAD

**Issue by oleksandrp1** [unickq/allure-nunit#44]
Cannot find "AllureNUnit" attribute after update of "NUnite.Allure" nuget package from 1.0.14 to 1.2.0
Error	CS0234	The type or namespace name 'Core' does not exist in the namespace 'NUnit.Allure' (are you missing an assembly reference?)
Error	CS0246	The type or namespace name 'AllureNUnitAttribute' could not be found (are you missing a using directive or an assembly reference?)

**Comment by unickq** [comment]
Interesting. What's the target framework?

**Comment by oleksandrp1** [comment]
.Net Core 3.1

**Comment by unickq** [comment]
Looks like it wasn't built properly.
Please try 1.2.0.1

**Comment by oleksandrp1** [comment]
Fixed. Thanks!
