### ISSUE TITLE
NullReferenceException in AllureStepAspect.WrapStep when some of the arguments are null

### ISSUE THREAD

**Issue by LazyPotato** [unickq/allure-nunit#45]
Hi, seems like there is a problem in [WrapStep](https://github.com/unickq/allure-nunit/blob/master/src/allure-nunit/Core/Steps/AllureStepAspect.cs) method  in line 23
`                stepName = stepName?.Replace("{" + i + "}", arguments[i].ToString());
`
Possible solution is to check argument for null and replace it with something like "{null}"

Thanks in advance

**Comment by unickq** [comment]
Do you have a sample code to reproduce it?

**Comment by LazyPotato** [comment]
Sure

    [AllureNUnit]
    public class Test1
    {
        [Test]
        public void NullCheck()
        {
            Method1("123");
            Method1(null);
        }

        [AllureStep("StepName")]
        public void Method1(string value)
        {
        }
    }


Method1("123"); passes, but Method1(null); fails

**Comment by unickq** [comment]
Fixed in [1.2.1.1](https://github.com/unickq/allure-nunit/releases/tag/1.2.1.1)
