### ISSUE TITLE
Get test result id

### ISSUE THREAD

**Issue by bloodgang94** [unickq/allure-nunit#46]
Hey! I have a need for the AddScreenDiff method, but it requires the uuid property of the TestResult class. Can you implement an open method or open the _testResultGuid property for reading?

**Comment by unickq** [comment]
Added wrapper method in [1.2.1.1](https://github.com/unickq/allure-nunit/releases/tag/1.2.1.1)
```cs
[Test]
public void DiffTest()
{
    AllureLifecycle.Instance.AddScreenDiff("logo.png", "logo.png", "logo.png");
}
```


See https://github.com/unickq/allure-nunit/blob/master/src/allure-nunit-tests/AllureDiffTest.cs for examples
