### ISSUE TITLE
How to enable adding Screen Diff

### ISSUE THREAD

**Issue by bloodgang94** [unickq/allure-nunit#49]
Thanks for the quick implementation, but I have a question.
I created a test, marked it with [AllureLabel("testType", "screenshotDiff")], but I don't have access to compare? It won't work?
I expect to see it 
![image](https://user-images.githubusercontent.com/63465285/149764382-d6abc7e7-5072-40b3-9e13-9dd112d779b6.png)
But I se 
![image](https://user-images.githubusercontent.com/63465285/149764510-91998312-7492-4595-a5e6-1adbb565d0ba.png)

**Comment by unickq** [comment]
_I have no idea how this works in base projects https://github.com/allure-framework/allure-csharp and https://github.com/allure-framework/allure2/tree/master/plugins/screen-diff-plugin.

I just wrapped allure-csharp method into nunit test.

If you can get sample allure-results dir where diff works - I can think how to implement it_

**Comment by unickq** [comment]
for now, the report this plugin generates is built from:
```json
{
  "uuid": "3df577a9-4df0-48a1-959d-f1753363ce50-tr-0-1006",
  "historyId": "allure_nunit_tests.AllureDiffTest.DiffTest",
  "fullName": "allure_nunit_tests.AllureDiffTest.DiffTest",
  "labels": [
    {
      "name": "thread",
      "value": "NonParallelWorker"
    },
    {
      "name": "host",
      "value": "MSI"
    },
    {
      "name": "package",
      "value": "allure_nunit_tests"
    },
    {
      "name": "testMethod",
      "value": "DiffTest"
    },

    {
      "name": "testType",
      "value": "screenshotDiff"
    },
    {
      "name": "testType",
      "value": "screenshotDiff"
    },
    {
      "name": "suite",
      "value": "Tests - ScreenDiff"
    },
    {
      "name": "parentSuite",
      "value": "Root Suite"
    }
  ],
  "links": [],
  "name": "Simple test with diff",
  "status": "passed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "DiffTest"
  },
  "stage": "finished",
  "steps": [
    {
      "name": "DiffTest",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [
        {
          "name": "expected",
          "source": "ade4793c61af42a7953a265eaeda96fc-attachment.png",
          "type": "image/png"
        },
        {
          "name": "actual",
          "source": "7e3a66d44a094025867947f4513ffc82-attachment.png",
          "type": "image/png"
        },
        {
          "name": "diff",
          "source": "b9a6b769a2204e0bb754c4be0397d065-attachment.png",
          "type": "image/png"
        },
        {
          "name": "Console Output",
          "source": "522e43fcc7614ba1911aa446b7ac04da-attachment.txt",
          "type": "text/plain"
        }
      ],
      "parameters": [],
      "start": 1642420485822,
      "stop": 1642420485840
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1642420485821,
  "stop": 1642420485843
}
```

**Comment by unickq** [comment]
@bloodgang94 

Actually, there's an option to make it work.
Use `[AllureNUnit(false)]`, this will prevent the creation of root step, so diffs gonna be added directly in testResults attachments list

![image](https://user-images.githubusercontent.com/6696821/149770817-191fe033-6608-4ae5-af22-ef88978efd78.png)

https://github.com/unickq/allure-nunit/wiki/Attachments#screen-diffs

**Comment by bloodgang94** [comment]
Can you give more details?
I made tests on the class, it has attributes AllureNunit (false) but the application did not work for me
![image](https://user-images.githubusercontent.com/63465285/149904147-03c980c3-dad8-423c-b639-3b385e7bef2a.png)

**Comment by unickq** [comment]
I added a link to docs above.

What does application did not work mean?

**Comment by bloodgang94** [comment]
I did as you suggested. I have the following structure
![image](https://user-images.githubusercontent.com/63465285/149918065-1564251f-01cb-4195-93d0-a9d3b98024cc.png)
But the plugin still didn't work.
[AllureLabel("testType", "screenshotDiff")] Shouldn't this be added to the test method?

**Comment by unickq** [comment]
here's an example https://github.com/unickq/allure-nunit/blob/master/src/allure-nunit-tests/AllureDiffTest.cs

please attach -tr- json from allure-results dir

> [AllureLabel("testType", "screenshotDiff")] Shouldn't this be added to the test method?

no

**Comment by bloodgang94** [comment]
This worked for me:
1. Added the [AllureName("..")] attribute to the test
2. Removed AllureLabel

Thanks!
