### ISSUE TITLE
AspectInjector.targets error in Rider 

### ISSUE THREAD

**Issue by Onebitl0st** [unickq/allure-nunit#50]
Hello!
Can't build solution in rider using DotNet SDK Builder 6.0.1, due to this error

AspectInjector.targets(93, 5): [MSB4062] The "Microsoft.Build.Tasks.GetFrameworkSdkPath" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

.NET SDK 6.0.101

Rider version Build #RD-213.6461.51, built on December 22, 2021

**Comment by unickq** [comment]
Hey. Try to use older build of allure-nunit. Or try to update aspect dep manually.

VS22 works with latest plugin version 🤷

or feel free to debug and create a pr to fix this weird behavior 👋

**Comment by Onebitl0st** [comment]
Thanks for the fast response.
Yeah, rollback is working.
And there is not really pr to allure-NUnit - it's more about AspectInjector - which is used as one of the dependencies :(
I'll try to create an issue there. As I can see, AspectInjector used a lot in code

**Comment by unickq** [comment]
Yep, it became a part of the project after Steps were merged.

I’ll check .net 6 when I have time

**Comment by Onebitl0st** [comment]
Thanks a lot!

**Comment by unickq** [comment]
please follow https://github.com/allure-framework/allure-csharp/tree/main/Allure.NUnit
