### ISSUE TITLE
Steps do not show in Setup

### ISSUE THREAD

**Issue by andrematosfundao** [unickq/allure-nunit#51]
Noticed that when using steps on the setup they are not showing up on the setup part of the logs. see image bellow.

we can have allure steps running on the nunit setup, i was just expecting them to show on the setup part of the logs. Am i doing something wrong or is this the way it works?

![image](https://user-images.githubusercontent.com/33062016/167164961-c6873a33-85da-4785-b2c2-1a469df734db.png)
code:

`using NUnit.Allure.Attributes;
using NUnit.Allure.Core;
using NUnit.Framework;

namespace SeleniumTests.tests
{

    [TestFixture]
    [AllureNUnit]
    [AllureSuite("experiment")]
    internal class TestExperiment
    {
        
        [SetUp]
        public void SetUp()
        {
            login();
        }

        [AllureStep("login")]
        private void login()
        {
            TestContext.WriteLine("login");
        }

        [AllureStep("test action")]
        private void action()
        {
            TestContext.WriteLine("action");
        }

        [Test]
        [AllureName("test1")]
        public void Test1()
        {
            action();
        }
    }
}`

nuget:
`
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit.Allure" Version="1.2.1.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.0" />
  </ItemGroup>
`

**Comment by unickq** [comment]
please follow https://github.com/allure-framework/allure-csharp/tree/main/Allure.NUnit
