### ISSUE TITLE
Edit and continue does not work due to usage of AspectInjector 2.6

### ISSUE THREAD

**Issue by andrematosfundao** [unickq/allure-nunit#52]
The AllureStepAttribute is using AspectInjector 2.6 which does not allow edit and continue while debugging in VisualStudio, this mak developing code much more difficult.

See gif of issue here:
[Recording](https://user-images.githubusercontent.com/33062016/203574171-9cb5e903-e89e-4be7-80a6-2047f06142b8.gif)

Test yourself with this code: [EditAndContinueIssue.zip](https://github.com/unickq/allure-nunit/files/10076507/EditAndContinueIssue.zip)

Currently I fixed this issue in my code by copying the code of the AllureStepAttribute into my project and using AspectInjector 2.7 library.

This issue would be fixed by updating allure-nunit to use the latest AspectInjector.

**Comment by vovsemenv** [comment]
Hello @andrematosfundao  currently allure-nunit is maintained in the another repo. https://github.com/allure-framework/allure-csharp/issues
Please consider opening issuer in the right repo

**Comment by andrematosfundao** [comment]
@vovsemenv  hey thanks

moved the issue there https://github.com/allure-framework/allure-csharp/issues/304
