### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by AsWeSee** [unickq/allure-nunit#6]
Allure adapter requires .NET framework 4.6.1 and Allure.Commons which requires Microsoft.Extensions.Configuration (>= 2.0.0) but Microsoft.Extensions.Configuration has no binaries for .net 4.6.1 and rejects installation (i tried via NuGet)

Is there exists another way to install allure adapter?

- Allure adapter version: 0.2.1

**Comment by unickq** [comment]
I've just created net461 project and installed NUnit.Allure 0.2.1 without any issues.

Microsoft.Extensions.Configuration is built for .NET Standard 2.0, which fully supported by net461:

https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/
> Broad platform support. .NET Standard 2.0 is supported on the following platforms:
> .NET Framework 4.6.1

After installation I got following packages.config file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Allure.Commons" version="2.2.0.7" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="2.0.0" targetFramework="net461" />
  <package id="MimeTypesMap" version="1.0.2" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
  <package id="NUnit" version="3.9.0" targetFramework="net461" />
  <package id="NUnit.Allure" version="0.2.1" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.4.0" targetFramework="net461" />
</packages>
```

Please let me know what issue you have

**Comment by AsWeSee** [comment]
After installation on clear project i got this
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Allure.Commons" version="2.2.0.7" targetFramework="net461" />
  <package id="NUnit" version="3.9.0" targetFramework="net461" />
  <package id="NUnit.Allure" version="0.2.1" targetFramework="net461" />
</packages>
```
Dependency is not installed. I can manually include MimeTypesMap, Json and Nunit, but Microsoft.Extensions still raises error. I asked another person to try to install (maybe problem only on my machine), but he got same error.

Tried Visual Studio 2017 and 2015, console application and WebApi, if it matters.

**Comment by unickq** [comment]
@AsWeSee 
Did you manage how to install dependencies of Allure.Commons?

**Comment by unickq** [comment]
@AsWeSee,
Microsoft.Extensions.Configuration is not the part of allure.commons anymore.
I'll update Allure.NUnit after https://github.com/allure-framework/allure-csharp/pull/11 merge
